<?php
/** @var Gorilla\Contact\Block\Contact $block */
?>
<form class="form contact"
      action="<?= $block->escapeUrl($block->getFormAction()) ?>"
      id="contact-form"
      method="post"
      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
      data-mage-init='{"validation":{}}'>

    <div class="field name required">
        <label class="label" for="name"><span><?= $block->escapeHtml(__('First Name')) ?></span></label>
        <div class="control">
            <input name="first_name" id="first_name" title="<?= $block->escapeHtmlAttr(__('First Name')) ?>" value="" class="input-text" type="text" data-validate="{required:true}"/>
        </div>
    </div>
    <div class="field name required">
        <label class="label" for="name"><span><?= $block->escapeHtml(__('Last Name')) ?></span></label>
        <div class="control">
            <input name="last_name" id="last_name" title="<?= $block->escapeHtmlAttr(__('Last Name')) ?>" value="" class="input-text" type="text" data-validate="{required:true}"/>
        </div>
    </div>
    <div class="field email required">
        <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
        <div class="control">
            <input name="email" id="email" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" value="" class="input-text" type="email" data-validate="{required:true, 'validate-email':true}"/>
        </div>
    </div>

    <div class="actions-toolbar">
        <div class="primary">
            <input type="hidden" name="hideit" id="hideit" value="" />
            <button type="submit" title="<?= $block->escapeHtmlAttr(__('Submit')) ?>" class="action submit primary">
                <span><?= $block->escapeHtml(__('Submit')) ?></span>
            </button>
        </div>
    </div>
</form>
